### ISSUE TITLE
Neighborhood Page - Wrong Page type is displayed

### ISSUE THREAD

**Issue by radu-constantin** [neighborhood-app/app#194]
When logging out and in as a different user, then creating a new neighborhood, and navigating to that neighborhood's page, the user context was still null, and so the NeighborhoodPageForMembers was displayed as opposed to NeighborhoodPageForAdmin. Here's some logs I did for debugging:

It may be worth looking into a solution without context unless this is an easy fix, I'm not sure.

**Comment by nina-dk** [comment]
Note that this is a duplicate of #192.

**Comment by radu-constantin** [comment]
Sorry about that. Will close!
