### ISSUE TITLE
Write route for viewing a single neighborhood

### ISSUE THREAD

**Issue by radu-constantin** [neighborhood-app/app#40]

**Comment by radu-constantin** [comment]
Route should be: /neighborhoods/:id

**Comment by MaxHass12** [comment]
To be done after we have created neighborhood.

**Comment by radu-constantin** [comment]
What do you mean by created neighborhood? I think we can start working on this route right now.

**Comment by MaxHass12** [comment]
I was thinking about handling 2-3 routes in same PR. Does that sound good?

Yes, you are correct we can start coding it right away.

**Comment by radu-constantin** [comment]
Yeah, I agree, we would have too many PR's otherwise
