### ISSUE TITLE
Create route for user logout

### ISSUE THREAD

**Issue by radu-constantin** [neighborhood-app/app#60]

**Comment by MaxHass12** [comment]
Seems like it is impossible to invalidate a jwt token since that token is not saved anywhere. Which means it's impossible to implement the logout functionality using jwt token.

https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6

**Comment by radu-constantin** [comment]
Hmm, I think we should just remove the token from local storage for now and implement a better solution on future iterations. What do you think?
