### ISSUE TITLE
Create view for viewing all neighborhoods

### ISSUE THREAD

**Issue by radu-constantin** [neighborhood-app/app#80]

**Comment by RobertRodes** [comment]
I have begun working on this, and posted a couple of files. This is very preliminary work. If you would like to see the files, they are in [the backend/public directory](https://github.com/neighborhood-app/app/tree/create-view-for-viewing-all-neighborhoods/apps/frontend/public), `test.html` and `test.js`. If you would like to see the code, do these:

1. Open Docker. Ensure that the `backend` container is running.
2. Open a terminal.
3. In the terminal, run `git checkout create-view-for-viewing-all-neighborhoods`.
4. Run `npm run server`.
5. Open another terminal.
6. Run `npm run client`.
7. Open a browser tab.
8. In that tab, navigate to `localhost:3000/test.html`.

You should see a table with the neighborhoods, as well as the name of each neighborhood's admin user pulled from the `users` table. The table is unformatted; at this point my goal was to display the correct data.

I did this by using POJ and the Fetch API to call existing routes and display them on a page in a table. I also added an html file to the `public` directory, which of course isn't the way we are doing things. But I wanted to get something up and running, and it will be easy enough to "Reactify" it once I (we?) get a clearer understanding of how we are setting things up.

Part of the reason that I didn't use React and React Router and the existing .css file was that I'm not completely confident that I should simply duplicate Radu's file structure for his Login Form. For example, I'd like to explore the idea of a master .css file before going too much further down the road. Each component can have its own .css file for styles exclusive to itself, but there are many styles in common that would be a headache to change down the road if we have them duplicated throughout many components. I'd also like to have a clearer picture of how we are defining what goes in the different `src` directories.
