### ISSUE TITLE
Restructure tests in describe blocks for each Route

### ISSUE THREAD

**Issue by radu-constantin** [neighborhood-app/app#82]

**Comment by MaxHass12** [comment]
What's with this?

**Comment by radu-constantin** [comment]
I didn't have the chance to talk about this. I think we should have a describe block for each separate route, since the tests are becoming cluttered now.
For example: a describe block for GET neighborhoods/:id, a separate one for POST neighborhoods, and so on.
What do you think?

**Comment by MaxHass12** [comment]
Yeah, definitely. That's how it should be.

**Comment by radu-constantin** [comment]
Done!
