### ISSUE TITLE
Revise the backend till now.

### ISSUE THREAD

**Issue by MaxHass12** [neighborhood-app/app#85]
Since we will have do a revision of the backend because we have to separate `routeHelpers` to `services`, may be we can do  just a brief revision of the code we have written till now.

For example: If we have created helpers which are redundant, write comments on functions, etc.

**Comment by MaxHass12** [comment]
Changes in the backend

[] 1. In the route GET /api/neighborhoods to get all neighborhoods, if no neighborhood is present we should return empty array instead of an error. (file `/src/controllers/neighborhood.ts`)

**Comment by radu-constantin** [comment]
Completed!
